<div class="gamesTable">
	<h4>Grupp A</h4>
	<table class="table table-striped table-condensed">
		<thead>
			<tr>
				<th>Lag</th>
				<th>S</th>
				<th>V</th>
				<th>O</th>
				<th>F</th>
				<th>P</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Polen</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
			</tr>
			<tr>
				<td>Grekland</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
			</tr>
			<tr>
				<td>Ryssland</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
			</tr>
			<tr>
				<td>Tjeckien</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
			</tr>
		</tbody>
	</table>
</div>