<div class="gamesTable">
	<h4>Grupp C</h4>
	<table class="table table-striped table-condensed">
		<thead>
			<tr>
				<th>Lag</th>
				<th>S</th>
				<th>V</th>
				<th>O</th>
				<th>F</th>
				<th>P</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Spanien</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
			</tr>
			<tr>
				<td>Italien</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
			</tr>
			<tr>
				<td>Irland</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
			</tr>
			<tr>
				<td>Kroatien</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
				<td>0</td>
			</tr>
		</tbody>
	</table>
</div>